######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:30:11 2015
######################################################################

TEMPLATE = app
TARGET = p6
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += validity.cpp
