######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:19:48 2015
######################################################################

TEMPLATE = app
TARGET = p10
INCLUDEPATH += .

# Input
SOURCES += converting.cpp
