######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 13:55:06 2015
######################################################################

TEMPLATE = app
TARGET = p9
INCLUDEPATH += .

# Input
SOURCES += julianday.cpp
