######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:35:17 2015
######################################################################

TEMPLATE = app
TARGET = p12
INCLUDEPATH += .

# Input
SOURCES += modify.cpp
