######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 09:54:41 2015
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
SOURCES += length.cpp
