######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 8 15:55:21 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += absolute.cpp

QT += widgets
