######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 15 16:27:00 2016
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
HEADERS += disconnect.h
SOURCES += disconnect.cpp main.cpp

QT += widgets
