######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 22 16:22:23 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += colours.h
SOURCES += colours.cpp main.cpp

QT += widgets
