######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 16:30:30 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp

QT += widgets
