######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:35:53 2015
######################################################################

TEMPLATE = app
TARGET = p7
INCLUDEPATH += .

# Input
SOURCES += daystofrom.cpp
