######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 19 10:35:57 2016
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
HEADERS += timer.h
SOURCES += main.cpp timer.cpp

QT += widgets
