######################################################################
# Automatically generated by qmake (3.0) Mo. Jan. 25 13:22:08 2016
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
HEADERS += puff.h
SOURCES += main.cpp puff.cpp

QT += widgets
