######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:16:03 2015
######################################################################

TEMPLATE = app
TARGET = p9
INCLUDEPATH += .

# Input
SOURCES += comparing.cpp
