######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 15:19:36 2016
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
SOURCES += list-dir.cpp
