######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 09:37:40 2015
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
SOURCES += main.cpp
