######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 15:16:36 2015
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += mylist.cpp
