######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 15:45:45 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += simple.cpp

QT += widgets
