######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:16:51 2015
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += leapyear.cpp

QT -= gui
