######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 12 16:28:46 2016
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
HEADERS += form.h
SOURCES += form.cpp main.cpp

QT += widgets
