######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:01:14 2015
######################################################################

TEMPLATE = app
TARGET = p6
INCLUDEPATH += .

# Input
SOURCES += building.cpp
