######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 15:53:43 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
SOURCES += pushbutton.cpp

QT += widgets
