######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 19 16:01:02 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += spinbox.h
SOURCES += main.cpp spinbox.cpp

QT += widgets
