######################################################################
# Automatically generated by qmake (2.01a) Mon May 11 23:01:03 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Taschenrechner.h
FORMS += Taschenrechner.ui
SOURCES += main.cpp Taschenrechner.cpp
