######################################################################
# Automatically generated by qmake (3.0) Mo. Jan. 25 15:31:03 2016
######################################################################

TEMPLATE = app
TARGET = customwidget
INCLUDEPATH += .

# Input
HEADERS += burning.h widget.h
SOURCES += burning.cpp main.cpp widget.cpp

QT += widgets
