######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 16:02:44 2015
######################################################################

TEMPLATE = app
TARGET = p6
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += book.h
SOURCES += book.cpp sortcustomclass.cpp
