######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 26 13:38:22 2016
######################################################################

TEMPLATE = app
TARGET = snake
INCLUDEPATH += .

# Input
HEADERS += snake.h
SOURCES += main.cpp snake.cpp

QT += widgets
