######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:46:36 2015
######################################################################

TEMPLATE = app
TARGET = p14
INCLUDEPATH += .

# Input
SOURCES += escape-h.cpp
