######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 09:28:31 2015
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets
