######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 12 15:54:51 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += buttons.h
SOURCES += buttons.cpp main.cpp

QT += widgets
