######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 29 09:34:33 2016
######################################################################

TEMPLATE = app
TARGET = breakout
INCLUDEPATH += .

# Input
HEADERS += ball.h breakout.h brick.h paddle.h
SOURCES += ball.cpp breakout.cpp brick.cpp main.cpp paddle.cpp

QT += widgets
