######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 10:51:10 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
SOURCES += write2file.cpp
