######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 22 14:32:30 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += splitter.h
SOURCES += main.cpp splitter.cpp

QT += widgets

CONFIG += c++11
