######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 15 15:49:28 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
HEADERS += click.h
SOURCES += click.cpp main.cpp

QT = widgets
