######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 16:12:59 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += plusminus.h
SOURCES += main.cpp plusminus.cpp

QT += widgets
