######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 19 16:18:51 2016
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
HEADERS += statusbar.h
SOURCES += main.cpp statusbar.cpp

QT += widgets
