######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 09:50:49 2015
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
SOURCES += main.cpp
