######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 09:48:02 2015
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
SOURCES += main.cpp
