######################################################################
# Automatically generated by qmake (3.0) Mo. Jan. 25 10:30:37 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += transparent_rectangles.h
SOURCES += main.cpp transparent_rectangles.cpp

QT += widgets
