######################################################################
# Automatically generated by qmake (3.0) Mo. Jan. 25 10:54:39 2016
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
HEADERS += donut.h
SOURCES += donut.cpp main.cpp

QT += widgets
