######################################################################
# Automatically generated by qmake (2.01a) Wed May 13 16:29:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MiniPaint.h
FORMS += MiniPaint.ui
SOURCES += main.cpp MiniPaint.cpp
