######################################################################
# Automatically generated by qmake (2.01a) Tue May 12 13:10:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h
FORMS += Calculator.ui
SOURCES += Calculator.cpp main.cpp
