######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:11:18 2015
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
SOURCES += compare-date.cpp
