######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 22 15:03:43 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp

QT += widgets
