######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 16:29:58 2015
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += file-size.cpp
