######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 15:44:51 2015
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += myqmap.cpp
