######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:06:03 2015
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
SOURCES += current.cpp
