######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 15:24:10 2015
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
SOURCES += mystringlist.cpp
