######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 8 15:55:10 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += skeleton.h
SOURCES += main.cpp skeleton.cpp
