######################################################################
# Automatically generated by qmake (3.0) Do. Jan. 21 10:32:45 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
HEADERS += listwidget.h
SOURCES += listwidget.cpp main.cpp

QT += widgets
