######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 13:05:37 2015
######################################################################

TEMPLATE = app
TARGET = p8
INCLUDEPATH += .

# Input
SOURCES += datetime.cpp
