######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 15 16:03:31 2016
######################################################################

TEMPLATE = app
TARGET = p3
INCLUDEPATH += .

# Input
HEADERS += move.h
SOURCES += main.cpp move.cpp

QT += widgets
