######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 22 15:31:08 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
HEADERS += lines.h
SOURCES += lines.cpp main.cpp

QT += widgets
