######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:03:19 2015
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += init.cpp
