######################################################################
# Automatically generated by qmake (3.0) Mo. Dez. 28 14:44:06 2015
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
