######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:04:22 2015
######################################################################

TEMPLATE = app
TARGET = p7
INCLUDEPATH += .

# Input
SOURCES += substrings.cpp
