######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 19 14:20:19 2016
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .

# Input
HEADERS += slider.h
SOURCES += main.cpp slider.cpp

QT += widgets
