######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 11:25:19 2015
######################################################################

TEMPLATE = app
TARGET = p5
INCLUDEPATH += .

# Input
SOURCES += dateformats.cpp
