######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 15 15:38:46 2016
######################################################################

TEMPLATE = app
TARGET = p7
INCLUDEPATH += .

# Input
HEADERS += review.h
SOURCES += main.cpp review.cpp

QT += widgets
