######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:41:42 2015
######################################################################

TEMPLATE = app
TARGET = p13
INCLUDEPATH += .

# Input
SOURCES += r-align.cpp
