######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 15:09:25 2015
######################################################################

TEMPLATE = app
TARGET = p1
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += myvector.cpp
