######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 15:35:48 2015
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += myset.cpp
