######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 8 16:05:16 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += verticalbox.h
SOURCES += main.cpp verticalbox.cpp

QT += widgets
