######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 19 15:25:30 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += combobox.h
SOURCES += combobox.cpp main.cpp

QT += widgets

CONFIG += c++11
