######################################################################
# Automatically generated by qmake (3.0) Fr. Jan. 15 15:57:01 2016
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
HEADERS += keypress.h
SOURCES += keypress.cpp main.cpp

QT += widgets
