######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 12 16:38:09 2016
######################################################################

TEMPLATE = app
TARGET = p6
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp

QT += widgets

CONFIG += c++11
