######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:10:08 2015
######################################################################

TEMPLATE = app
TARGET = p8
INCLUDEPATH += .

# Input
SOURCES += looping.cpp
