######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 10:27:40 2015
######################################################################

TEMPLATE = app
TARGET = p11
INCLUDEPATH += .

# Input
SOURCES += letters.cpp
