######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 29 16:40:15 2015
######################################################################

TEMPLATE = app
TARGET = p2
INCLUDEPATH += .

# Input
SOURCES += read-file.cpp
