######################################################################
# Automatically generated by qmake (3.0) Di. Jan. 12 16:17:51 2016
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
HEADERS += nesting.h
SOURCES += main.cpp nesting.cpp

QT += widgets
