######################################################################
# Automatically generated by qmake (3.0) Mi. Jan. 6 10:55:10 2016
######################################################################

TEMPLATE = app
TARGET = p4
INCLUDEPATH += .

# Input
SOURCES += copy-file.cpp
